# Generated by Django 4.2.8 on 2024-05-20 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SD_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savingproduct',
            name='subscribe_user',
            field=models.ManyToManyField(related_name='subscribed_saving', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depositproduct',
            name='subscribe_user',
            field=models.ManyToManyField(related_name='subscribed_deposit', to=settings.AUTH_USER_MODEL),
        ),
    ]
